parameters:
  ServiceConnection:

stages:
- stage: build
  displayName: Build Image
  jobs:
  - job: build_image
    displayName: Build Image
    pool:
      name: 'DAS - Continuous Integration'
      demands: Agent.OS -equals Windows_NT
    steps:
      - task: gittools.gitversion.gitversion-task.GitVersion@5
        displayName: GitVersion
        inputs:
          configFilePath: GitVersion.yml
          updateAssemblyInfo: true

      - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
        parameters:
          ContainerRegistryName: $(PublicAcrName)
          ServiceConnection: ${{ parameters.ServiceConnection }}
          ImageName: das-tools-service
          BranchToCreateLatestTag: master

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          contents: |
            azure/**
            manifests/**
          targetFolder: '$(build.artifactstagingdirectory)/publish'

  - job: 'build_dacpac'
    pool:
      name: 'DAS - Continuous Integration Agents'
    workspace:
      clean: all
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build DACPAC
      inputs:
        projects: 'src/SFA.DAS.ToolService.Database/SFA.DAS.ToolService.Database.sqlproj'
        arguments: '/p:NetCoreBuild=true --configuration $(buildConfiguration) -o $(build.artifactstagingdirectory)/publish'

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Artifact: database'
      inputs:
        targetPath: '$(build.artifactstagingdirectory)/publish'
        artifactName: database
