parameters:
  ServiceConnection:

stages:
- stage: build
  displayName: Build Image
  jobs:
  - job: build_image
    displayName: Build Image
    pool:
      name: 'DAS - Continuous Integration'
      demands: Agent.OS -equals Windows_NT
    steps:
      - task: gittools.gitversion.gitversion-task.GitVersion@5
        displayName: GitVersion
        inputs:
          configFilePath: GitVersion.yml
          updateAssemblyInfo: true

      - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
        parameters:
          ContainerRegistryName: $(PublicAcrName)
          ServiceConnection: ${{ parameters.ServiceConnection }}
          ImageName: das-tools-service
          BranchToCreateLatestTag: master

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          contents: |
            azure/**
            manifests/**
          targetFolder: '$(build.artifactstagingdirectory)/publish'

  - job: build_dacpac
    displayName: Build DACPAC
    pool:
      name: 'DAS - Continuous Integration'
      demands: Agent.OS -equals Windows_NT
    workspace:
      clean: all
    steps:
      - task: VSBuild@1
        displayName: 'Build DACPAC'
        inputs:
          solution: 'src\**\*.sqlproj'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          msbuildArgs: '/p:PackageLocation="$(build.artifactstagingdirectory)/publish"'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          Contents: |
            src\**\*.dacpac
          TargetFolder: '$(build.artifactstagingdirectory)/publish'
          OverWrite: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)/publish'
          artifactName: database
