stages:
- stage: build
  displayName: Build Image
  jobs:
  - job: build_image
    displayName: Build Image
    pool:
      name: 'DAS - Continuous Integration'
      demands: Agent.OS -equals Windows_NT
    steps:
      - task: gittools.gitversion.gitversion-task.GitVersion@5
        displayName: GitVersion
        inputs:
          configFilePath: GitVersion.yml
          updateAssemblyInfo: true

      - task: AzureCLI@2
        displayName: 'Build Image'
        inputs:
          azureSubscription: 'SFA-DAS-DevTest-ARM'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: 'az acr build --registry daspocsharedcr --image das-tools-service:$(build.buildnumber) $(Agent.BuildDirectory)'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          contents: |
            azure/**
            manifests/**
          targetFolder: '$(build.artifactstagingdirectory)/publish'

  - job: 'build_dacpac'
    pool:
      name: 'DAS - Continuous Integration'
      demands: Agent.OS -equals Windows_NT
    workspace:
      clean: all
    steps:
    - task: VSBuild@1
      displayName: 'Build DACPAC'
      inputs:
        solution: 'src/SFA.DAS.ToolService.Database/SFA.DAS.ToolService.Database.sqlproj'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '/p:PackageLocation="$(build.artifactstagingdirectory)/publish"'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        contents: |
          src/**/*.dacpac
        targetFolder: '$(build.artifactstagingdirectory)/publish'

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Artifact: database'
      inputs:
        targetPath: '$(build.artifactstagingdirectory)/publish'
        artifactName: database
