trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - manifests/*
      - src/*
      - azure-pipelines.yml
      - Dockerfile

pr: none

variables:
  - group: 'Dev Management Resources'

stages:
- template: /pipeline-templates/stage/build.yml
