resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.2.6
    endpoint: SFA
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.2.3
    endpoint: SFA

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - manifests/*
      - src/*
      - azure-pipelines.yml
      - Dockerfile

pr: none

variables:
- name: ServiceName
  value: tools

stages:
- template: /pipeline-templates/stage/build.yml

- stage: DeployTo_DEV
  displayName: DeployTo_DEV
  variables:
  - group: Release Management Resources
  - group: Dev Management Resources
  - group: TEST Shared Resources
  - group: Tools - ENV - TEST
  jobs:
  - template: /pipeline-templates/job/deploy.yml
    parameters:
      AksResourceGroup: $(AKSResourceGroupName)
      DatabaseName: $(DatabaseName)
      Environment: DEV
      KubernetesCluster: $(AKSSharedClusterName)
      KubectlVersion: 1.18.8
      ResourceGroupLocation: $(ResourceGroupLocation)
      ServiceConnection: SFA-DAS-DevTest-ARM
      SharedSQLServerFQDN: $(SharedSQLServerFQDN)
      SharedSQLServerPassword: $(SharedSQLServerPassword)
      SharedSQLServerUsername: $(SharedSQLServerUsername)
      SubscriptionId: $(SubscriptionId)
