resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.2.19
    endpoint: SFA
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.2.7
    endpoint: SFA

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - manifests/*
      - pipeline-templates/*
      - src/*
      - azure-pipelines.yml
      - Dockerfile

pr: none

variables:
- name: DatabaseConnectionString
  value: Server=tcp:$(SharedSQLServerFQDN),1433;Database=das-$(ResourceEnvironmentName)-$(ServiceName)-db;User ID=$(SQLServerServiceAccountUsername);Password=$(SQLServerServiceAccountPassword);Trusted_Connection=False;Pooling=False;Connect Timeout=200;MultipleActiveResultSets=True
- name: KubectlVersion
  value: 1.18.8
- name: ServiceName
  value: tools


stages:
- template: /pipeline-templates/stage/build.yml

- stage: DeployTo_DEV
  displayName: DeployTo_DEV
  variables:
  - group: Release Management Resources
  - group: Dev Management Resources
  - group: TEST Shared Resources
  - group: Tools - ENV - TEST
  ##TO DO: update IngressHost value in 'Tools - ENV - TEST' and remove from pipeline file
  - name: IngressHost
    value: test-tools.apprenticeships.education.gov.uk
  jobs:
  - template: /pipeline-templates/job/deploy.yml
    parameters:
      AksResourceGroup: $(AKSResourceGroupName)
      AppGatewayName: $(AKSSharedAppGatewayName)
      AppGatewayResourceGroup: $(AKSSharedNodeResourceGroupName)
      Environment: DEV
      KeyVaultName: $(SharedKeyVaultName)
      KubernetesCluster: $(AKSSharedClusterName)
      KubectlVersion: $(KubectlVersion)
      ResourceGroupLocation: $(ResourceGroupLocation)
      ServiceConnection: SFA-DAS-DevTest-ARM
      SharedSQLServerFQDN: $(SharedSQLServerFQDN)
      SharedSQLServerPassword: $(SharedSQLServerPassword)
      SharedSQLServerUsername: $(SharedSQLServerUsername)
      SubscriptionId: $(SubscriptionId)

- stage: DeployTo_PROD
  displayName: DeployTo_PROD
  variables:
  - group: Release Management Resources
  - group: Prod Management Resources
  - group: PROD Shared Resources
  - group: Tools - ENV - PROD
  jobs:
  - template: /pipeline-templates/job/deploy.yml
    parameters:
      AksResourceGroup: $(AKSResourceGroupName)
      AppGatewayName: $(AKSSharedAppGatewayName)
      AppGatewayResourceGroup: $(AKSSharedNodeResourceGroupName)
      Environment: PROD
      KeyVaultName: $(SharedKeyVaultName)
      KubernetesCluster: $(AKSSharedClusterName)
      KubectlVersion: $(KubectlVersion)
      ResourceGroupLocation: $(ResourceGroupLocation)
      ServiceConnection: SFA-DIG-Prod-ARM
      SharedSQLServerFQDN: $(SharedSQLServerFQDN)
      SharedSQLServerPassword: $(SharedSQLServerPassword)
      SharedSQLServerUsername: $(SharedSQLServerUsername)
      SubscriptionId: $(SubscriptionId)
