resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.63
    endpoint: SFA
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.0.4
    endpoint: SFA

trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
      - manifests/*
      - pipeline-templates/*
      - src/*
      - azure-pipelines.yml
      - Dockerfile

variables:
- name: KubectlVersion
  value: 1.18.8
- name: ServiceName
  value: tools
- group : Release Management Resources

stages:
- template: /pipeline-templates/stage/build.yml
  parameters:
    ServiceConnection: SFA-DIG-Prod-ARM

- stage: DeployTo_DEV
  displayName: DeployTo_DEV
  variables:
  - group: Dev Management Resources
  - group: TEST Shared Resources
  - group: DEV Tools Service Shared
  jobs:
  - template: /pipeline-templates/job/deploy.yml
    parameters:
      AksResourceGroup: $(AKSResourceGroupName)
      AppGatewayName: $(AKSSharedAppGatewayName)
      AppGatewayResourceGroup: $(AKSSharedNodeResourceGroupName)
      Environment: DEV
      KeyVaultName: $(SharedKeyVaultName)
      KubernetesCluster: $(AKSSharedClusterName)
      KubectlVersion: $(KubectlVersion)
      ResourceGroupLocation: $(ResourceGroupLocation)
      ServiceConnection: SFA-DAS-DevTest-ARM
      SharedSQLServerFQDN: $(SharedSQLServerFQDN)
      SharedSQLServerPassword: $(SharedSQLServerPassword)
      SharedSQLServerUsername: $(SharedSQLServerUsername)
      SubscriptionId: $(SubscriptionId)

- stage: DeployTo_PREPROD
  displayName: DeployTo_PREPROD
  variables:
  - group: PreProd Management Resources
  - group: PREPROD Shared Resources
  - group: PREPROD Tools Service Shared
  jobs:
  - template: /pipeline-templates/job/deploy.yml
    parameters:
      AksResourceGroup: $(AKSResourceGroupName)
      AppGatewayName: $(AKSSharedAppGatewayName)
      AppGatewayResourceGroup: $(AKSSharedNodeResourceGroupName)
      Environment: PREPROD
      KeyVaultName: $(SharedKeyVaultName)
      KubernetesCluster: $(AKSSharedClusterName)
      KubectlVersion: $(KubectlVersion)
      ResourceGroupLocation: $(ResourceGroupLocation)
      ServiceConnection: SFA-DIG-PreProd-ARM
      SharedSQLServerFQDN: $(SharedSQLServerFQDN)
      SharedSQLServerPassword: $(SharedSQLServerPassword)
      SharedSQLServerUsername: $(SharedSQLServerUsername)
      SubscriptionId: $(SubscriptionId)

- stage: DeployTo_PROD
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: DeployTo_PROD
  variables:
  - group: Prod Management Resources
  - group: PROD Shared Resources
  - group: PROD Tools Service Shared
  jobs:
  - template: /pipeline-templates/job/deploy.yml
    parameters:
      AksResourceGroup: $(AKSResourceGroupName)
      AppGatewayName: $(AKSSharedAppGatewayName)
      AppGatewayResourceGroup: $(AKSSharedNodeResourceGroupName)
      Environment: PROD
      KeyVaultName: $(SharedKeyVaultName)
      KubernetesCluster: $(AKSSharedClusterName)
      KubectlVersion: $(KubectlVersion)
      ResourceGroupLocation: $(ResourceGroupLocation)
      ServiceConnection: SFA-DIG-Prod-ARM
      SharedSQLServerFQDN: $(SharedSQLServerFQDN)
      SharedSQLServerPassword: $(SharedSQLServerPassword)
      SharedSQLServerUsername: $(SharedSQLServerUsername)
      SubscriptionId: $(SubscriptionId)
