parameters:
  AksResourceGroup: 
  DatabaseName: 
  Environment: 
  KubernetesCluster: 
  KubectlVersion: 
  ResourceGroupLocation: 
  ServiceConnection: 
  SharedSQLServerFQDN: 
  SharedSQLServerPassword: 
  SharedSQLServerUsername:
  SubscriptionId: 

jobs:
- deployment: DeployTo_${{ parameters.Environment }}
  environment: ${{ parameters.Environment }}
  pool:
    name: 'DAS - Continuous Integration'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: 'das-tools-service/'
        - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
          parameters:
            Location: ${{ parameters.ResourceGroupLocation }}
            ParametersPath: $(Pipeline.Workspace)/das-tools-service/azure/template.parameters.json
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: ${{ parameters.SubscriptionId }}
            TemplatePath: $(Pipeline.Workspace)/das-tools-service/azure/template.json
            IsMultiRepoCheckout: true
        - task: replacetokens@3
          inputs:
            rootDirectory: '$(Pipeline.Workspace)/das-tools-service/manifests'
            targetFiles: '**/*.yml'
            encoding: 'auto'
            writeBOM: true
            actionOnMissing: 'fail'
            keepToken: false
            tokenPrefix: '{{'
            tokenSuffix: '}}'
        - task: SqlAzureDacpacDeployment@1
          displayName: 'Deploy DACPAC'
          inputs:
            azureSubscription: ${{ parameters.ServiceConnection }}
            ServerName: '${{ parameters.SharedSQLServerFQDN }}'
            DatabaseName: '${{ parameters.DatabaseName }}'
            SqlUsername: '${{ parameters.SharedSQLServerUsername }}'
            SqlPassword: '${{ parameters.SharedSQLServerPassword }}'
            DacpacFile: '$(Pipeline.Workspace)/database/src/SFA.DAS.ToolService.Database/bin/Output/SFA.DAS.ToolService.Database.dacpac'
        - task: KubectlInstaller@0
          displayName: 'Install Kubectl ${{ parameters.KubectlVersion }}'
          inputs:
            kubectlVersion: ${{ parameters.KubectlVersion }}
        - task: Kubernetes@1
          displayName: 'Deploy Ingress Config'
          inputs:
            azureSubscriptionEndpoint: ${{ parameters.ServiceConnection }}
            azureResourceGroup: ${{ parameters.AksResourceGroup }}
            connectionType: Azure Resource Manager
            kubernetesCluster: ${{ parameters.KubernetesCluster }}
            namespace: engineering
            command: apply
            useConfigurationFile: true
            configuration: '$(Pipeline.Workspace)/das-tools-service/manifests/ingress-config'
            useClusterAdmin: true
        - task: Kubernetes@1
          displayName: 'Deploy Ingress'
          inputs:
            azureSubscriptionEndpoint: ${{ parameters.ServiceConnection }}
            azureResourceGroup: ${{ parameters.AksResourceGroup }}
            connectionType: Azure Resource Manager
            kubernetesCluster: ${{ parameters.KubernetesCluster }}
            namespace: engineering
            command: apply
            useConfigurationFile: true
            configuration: '$(Pipeline.Workspace)/das-tools-service/manifests/ingress.yml'
            useClusterAdmin: true
        - task: Kubernetes@1
          displayName: 'Create Shared ConfigMap'
          inputs:
            azureSubscriptionEndpoint: ${{ parameters.ServiceConnection }}
            azureResourceGroup: ${{ parameters.AksResourceGroup }}
            connectionType: Azure Resource Manager
            kubernetesCluster: ${{ parameters.KubernetesCluster }}
            namespace: engineering
            command: apply
            useConfigurationFile: true
            configuration: '$(Pipeline.Workspace)/das-tools-service/manifests/shared-config.yml'
            useClusterAdmin: true
        - task: Kubernetes@1
          displayName: 'Create Deployment'
          inputs:
            azureSubscriptionEndpoint: ${{ parameters.ServiceConnection }}
            azureResourceGroup: ${{ parameters.AksResourceGroup }}
            connectionType: Azure Resource Manager
            kubernetesCluster: ${{ parameters.KubernetesCluster }}
            namespace: engineering
            command: apply
            useConfigurationFile: true
            configuration: '$(Pipeline.Workspace)/das-tools-service/manifests/deployment.yml'
            useClusterAdmin: true
