---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: das-tool-service-web
    service: das-tool-service
  name: das-tool-service-web
  namespace: {{Namespace}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: das-tool-service-web
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: das-tool-service-web
    version: {{buildNumber}}
    service: das-tool-service
  name: das-tool-service-web
  namespace: {{Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: das-tool-service-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: das-tool-service-web
        service: das-tool-service
    spec:
      containers:
      - env:
        - name: ConfigurationStorageConnectionString
          value: {{ConfigurationStorageConnectionString}}
        - name: LoggingRedisConnectionString
          value: {{LoggingRedisConnectionString}}
        - name: LoggingRedisKey
          value: logstash
        - name: EnvironmentName
          value: {{EnvironmentName}}
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: {{appInsightsInstrumentationkey}}
        - name: Cdn__Url
          value: {{CdnUrl}}
        - name: Authentication__Domain
          value: {{Auth0Domain}}
        - name: Authentication__ClientId
          value: {{Auth0ClientId}}
        - name: Authentication__ClientSecret
          value: {{AUth0ClientSecret}}
        - name: Authentication__ManagementApiClientId
          value: {{ManagementApiClientId}}
        - name: Authentication__ManagementApiClientSecret
          value: {{ManagementApiClientSecret}}
        - name: RedisConnectionString
          value: {{RedisConnectionString}}
        - name: DatabaseConnectionString
          value: {{DatabaseConnectionString}}
        - name: DfESigninAddress
          value: {{DfeSignInAddress}}
        image: apprenticeshipsdevops/das-tools-service:{{buildNumber}}
        imagePullPolicy: IfNotPresent
        name: das-tool-service
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
            requests:
              cpu: 25m
              memory: 512Mi
