---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: das-tool-service-web
    service: das-tool-service
  name: das-tool-service-svc
  namespace: {{Namespace}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: das-tool-service-web
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: das-tool-service-web
    version: {{buildNumber}}
    service: das-tool-service
  name: das-tool-service-web
  namespace: {{Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: das-tool-service-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: das-tool-service-web
        service: das-tool-service
    spec:
      containers:
      - env:
        - name: ConfigurationStorageConnectionString
          value: {{ConfigurationStorageConnectionString}}
        - name: LoggingRedisConnectionString
          value: {{LoggingRedisConnectionString}}
        - name: LoggingRedisKey
          value: logstash
        - name: EnvironmentName
          value: {{EnvironmentName}}
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: TBA
        - name: Cdn__Url
          value: https://das-test-frnt-end.azureedge.net
        - name: Authentication__Auth0__Domain
          value: dfe-apprenticeships.eu.auth0.com
        - name: Authentication__Auth0__ClientId
          value: {{Auth0ClientId}}
        - name: Authentication__Auth0__ClientSecret
          value: {{AUth0ClientSecret}}
        - name: RedisConnectionString
          value: {{RedisConnectionString}}
        image: apprenticeshipsdevops/das-tools-service:{{buildNumber}}
        imagePullPolicy: IfNotPresent
        name: das-tool-service
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
            requests:
              cpu: 25m
              memory: 512Mi
