---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: das-tool-service-redirectscheme
  namespace: {{Namespace}}
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: das-tool-service-web
  namespace: {{Namespace}}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host('{{IngressHost}}')
      kind: Rule
      priority: 1
      services:
        - name: das-tool-service-web
          port: 80
          healthCheck:
            path: /health
            host: {{IngressHost}}
            intervalSeconds: 7
            timeoutSeconds: 60
      middlewares:
        - name: das-tool-service-redirectscheme
  tls:
    secretName: {{TlsSecretName}}
