apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: das-tool-service-web
  namespace: {{KubernetesNamespace}}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{TlsSecretName}}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-path: "/health"
spec:
  rules:
  - host: {{IngressHost}}
    http:
      paths:
      - path: /
        backend:
          serviceName: das-tool-service-web
          servicePort: 80