apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: das-tool-service-web
  namespace: {{KubernetesNamespace}}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{TlsSecretName}}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-path: "/health"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200"
    appgw.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - host: {{IngressHost}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: das-tool-service-web
                port:
                  number: 80
