apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: das-tool-service-web
  namespace: engineering
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{TlsSecretName}}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: das-tool-service-web
          servicePort: 80
          healthCheck:
            path: /health
            host: {{IngressHost}}
            intervalSeconds: 7
            timeoutSeconds: 60
