---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: das-tool-service-tlsoption
  namespace: {{Namespace}}
spec:
  minVersion: VersionTLS12

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: das-tool-service-redirectscheme
  namespace: {{Namespace}}
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: das-tool-service-web
  namespace: {{Namespace}}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{IngressHost}}`)
      kind: Rule
      priority: 1
      services:
        - name: das-tool-service-web
          port: 80
          healthCheck:
            path: /health
            host: {{IngressHost}}
            intervalSeconds: 7
            timeoutSeconds: 60
    - match: Host(`{{IngressHost}}`) && PathPrefix(`/messages`)
      kind: Rule
      priority: 2
      services:
        - name: das-secure-message-service-web
          port: 80
          healthCheck:
            path: /messages/health
            host: {{IngressHost}}
            intervalSeconds: 7
            timeoutSeconds: 60
      middlewares:
        - name: das-tool-service-redirectscheme
    - match: Host(`{{IngressHost}}`) && PathPrefix(`/api/messages`)
      kind: Rule
      priority: 3
      services:
        - name: das-secure-message-service-api
          port: 80
          healthCheck:
            path: /api/messages/health
            host: {{IngressHost}}
            intervalSeconds: 7
            timeoutSeconds: 60
      middlewares:
        - name: das-tool-service-redirectscheme
    - match: Host(`{{IngressHost}}`) && PathPrefix(`/grafana`)
      kind: Rule
      priority: 4
      services:
        - name: grafana
          port: 80
          healthCheck:
            path: /grafana/api/health
            host: {{IngressHost}}
            intervalSeconds: 7
            timeoutSeconds: 60
      middlewares:
        - name: das-tool-service-redirectscheme
  tls:
    secretName: {{TlsSecretName}}
    options:
      name: das-tool-service-tlsoption
      namespace: {{Namespace}}
