apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    service: das-tool-service
  name: das-tool-service-shared-config
  namespace: {{KubernetesNamespace}}
data:
  Logging__LogLevel__Default: Information
  Logging__LogLevel__System: Information
  Logging__LogLevel__Microsoft: Information
  ApplicationInsights__LogLevel__Default: Information
  Cdn__Url: {{CdnUrl}}
  BaseUrl: {{IngressHost}}
  ConfigurationStorageConnectionString: {{ConfigurationStorageConnectionString}}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ARMOUTPUTS_APPINSIGHTSINSTRUMENTATIONKEY}}
  EnvironmentName: {{EnvironmentName}}
  LoggingRedisConnectionString: {{LoggingRedisConnectionString}}
  LoggingRedisKey: logstash
  RedisConnectionString: {{RedisConnectionString}}
  RedisKey: das-tools-notification
